Applying MEQP1 Standard with phpcbf command
mailchimp/mc-magento pull request #1009
Opened 2019-07-24 17:20 UTC by roberto-ebizmarts

Applying MEQP1 Standard with phpcbf command

2019-07-25 16:47 UTC, SantiParagarino requested changes

2019-07-25 16:47 UTC, Santiagoebizmarts commented on app/code/community/Ebizmarts/MailChimp/Helper/Data.php
> +        if ($syncFlagDataArray[Ebizmarts_MailChimp_Model_System_Config_Source_Account::SYNC_FLAG_STATUS]!= Ebizmarts_MailChimp_Model_System_Config_Source_Account::IN_PROGRESS
Line exceeds 120 characters.

2019-07-25 16:47 UTC, Santiagoebizmarts commented on app/code/community/Ebizmarts/MailChimp/Helper/Data.php
> +            if ($syncFlagDataArray[Ebizmarts_MailChimp_Model_System_Config_Source_Account::SYNC_FLAG_STATUS]== Ebizmarts_MailChimp_Model_System_Config_Source_Account::FINISHED
Line exceeds 120 characters.

2019-07-25 16:47 UTC, Santiagoebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php
> +                    } elseif ($subscriber->getSubscriberStatus() !=                        Mage_Newsletter_Model_Subscriber::STATUS_UNSUBSCRIBED
Line exceeds 120 characters.

2019-07-25 16:47 UTC, Santiagoebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php
> +                    if ($subscriber->getSubscriberStatus() !=                        Mage_Newsletter_Model_Subscriber::STATUS_UNSUBSCRIBED
Line exceeds 120 characters.

2019-07-25 16:47 UTC, Santiagoebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/Store.php
> +     *
Why extra line?

2019-07-26 13:25 UTC, roberto-ebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
> +                || $dataProduct->getMailchimpSyncError() ==Ebizmarts_MailChimp_Model_Api_Products::PRODUCT_DISABLED_IN_MAGENTO
Solved with a variable saving Ebizmarts_MailChimp_Model_Api_Products::PRODUCT_DISABLED_IN_MAGENTO

2019-07-26 13:27 UTC, roberto-ebizmarts commented on app/code/community/Ebizmarts/MailChimp/Helper/Data.php
> +            if ($syncFlagDataArray[Ebizmarts_MailChimp_Model_System_Config_Source_Account::SYNC_FLAG_STATUS]== Ebizmarts_MailChimp_Model_System_Config_Source_Account::FINISHED
Solved

2019-07-26 13:32 UTC, roberto-ebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
> +                || $dataProduct->getMailchimpSyncError() !=                Ebizmarts_MailChimp_Model_Api_Products::PRODUCT_DISABLED_IN_MAGENTO
Solved with variable created saving: Ebizmarts_MailChimp_Model_Api_Products::PRODUCT_DISABLED_IN_MAGENTO

2019-07-26 13:37 UTC, roberto-ebizmarts commented on app/code/community/Ebizmarts/MailChimp/Helper/Data.php
> +        if ($syncFlagDataArray[Ebizmarts_MailChimp_Model_System_Config_Source_Account::SYNC_FLAG_STATUS]!= Ebizmarts_MailChimp_Model_System_Config_Source_Account::IN_PROGRESS
Solved:
$syncFlagStatus = Ebizmarts_MailChimp_Model_System_Config_Source_Account::SYNC_FLAG_STATUS;
        $inProgress = Ebizmarts_MailChimp_Model_System_Config_Source_Account::IN_PROGRESS

2019-07-26 13:37 UTC, SantiParagarino requested changes

2019-07-26 13:37 UTC, Santiagoebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php
> +                    if ($subscriber->getSubscriberStatus() != Mage_Newsletter_Model_Subscriber::STATUS_UNSUBSCRIBED
Reuse same variable $statusUnsubscribed as above.

2019-07-26 13:37 UTC, roberto-ebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php
> +                    } elseif ($subscriber->getSubscriberStatus() !=                        Mage_Newsletter_Model_Subscriber::STATUS_UNSUBSCRIBED
Solved:
$statusUnsubscribed = Mage_Newsletter_Model_Subscriber::STATUS_UNSUBSCRIBED;

2019-07-26 13:38 UTC, roberto-ebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php
> +                    if ($subscriber->getSubscriberStatus() !=                        Mage_Newsletter_Model_Subscriber::STATUS_UNSUBSCRIBED
Solved

2019-07-26 13:39 UTC, roberto-ebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/Store.php
> +     *
Solved

2019-07-26 13:40 UTC, roberto-ebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/Api/Carts.php
> +        /**
Solved

2019-07-26 13:48 UTC, roberto-ebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php
> +                    if ($subscriber->getSubscriberStatus() != Mage_Newsletter_Model_Subscriber::STATUS_UNSUBSCRIBED
Done.

2019-07-26 14:29 UTC, SantiParagarino approved these changes

2019-07-26 14:31 UTC, merged