Lucia codesniffer meqp1
mailchimp/mc-magento pull request #781
Opened 2018-08-27 14:11 UTC by luciaebizmarts

cs #779 Compliance for ECG and MEQP coding standards

2018-08-27 14:42 UTC, SantiParagarino requested changes

2018-08-27 14:42 UTC, Santiagoebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
> +            } elseif ($item->getProductType() == $this->typBundle() || $item->getProductType() == $this->typGrouped()) {
Fix typo in typBundle and typGrouped.

2018-08-27 14:42 UTC, Santiagoebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
> +     * @return false|Mage_Core_Model_Abstract
return type: Ebizmarts_MailChimp_Model_Api_Customers

2018-08-27 14:42 UTC, Santiagoebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
> +     * @return false|Mage_Core_Model_Abstract
Return type: Mage_Directory_Model_Country

2018-08-27 14:42 UTC, Santiagoebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
> +     * @return false|Mage_Core_Model_Abstract
Return type: Ebizmarts_MailChimp_Model_Api_Products

2018-08-27 14:42 UTC, Santiagoebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/Api/Stores.php
> +                    Mage::throwException('Please, change the general email in Store Email Addresses/General Contact');
Add translation as follows: $helper->__('Text');

2018-08-27 14:42 UTC, Santiagoebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/Api/Stores.php
> +            Mage::throwException('You don\'t have any lists configured in MailChimp');
Add translation as follows: $helper->__('Text');

2018-08-27 14:42 UTC, Santiagoebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/Email/Template.php
> +            $this->makeMandrillHelper()->log("store: $storeId API: " . $storeConfig, $storeId);
Add translation as follows: $helper->__('Text');

2018-08-27 18:20 UTC, centerax requested changes

2018-08-29 13:46 UTC, centerax requested changes

2018-08-29 13:46 UTC, centerax commented on app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
> +/*
delete commented code.

2018-08-29 13:46 UTC, centerax commented on app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
> +                ++$this->_counter;
leave as it was

2018-08-29 13:46 UTC, centerax commented on app/code/community/Ebizmarts/MailChimp/Model/Api/PromoCodes.php
> +        $maChimpSyncDel = "' AND mailchimp_sync_deleted = 1";
verify that strings are same

2018-08-29 13:46 UTC, centerax commented on app/code/community/Ebizmarts/MailChimp/Model/Api/Stores.php
> +                    $urlA = "'https://docs.magento.com/m1/ce/user_guide/search_seo/seo-url-rewrite-configure.html'";
use " or ', only one.

2018-08-29 13:46 UTC, centerax commented on app/code/community/Ebizmarts/MailChimp/Model/Api/Stores.php
> +                    $strB = ($strC . ' Possible solutions ');
remove `(`

2018-08-29 13:46 UTC, centerax commented on app/code/community/Ebizmarts/MailChimp/Model/Api/Stores.php
> +                    $errorMessage = $helper->__($strA . $strB . $str);
check string is same

2018-08-29 13:46 UTC, centerax commented on app/code/community/Ebizmarts/MailChimp/Model/Email/Queue.php
> +                        $message->setProcessedAt(Mage::getSingleton('core/date')->gmtDate());
check that are same and extract

2018-09-19 13:30 UTC, centerax approved these changes

2019-01-18 16:30 UTC, closed without merging