Issue978
mailchimp/mc-magento pull request #981
Opened 2019-06-14 19:24 UTC by brian-ebizmarts

closes #978

2019-06-14 19:41 UTC, SantiParagarino requested changes

2019-06-14 19:41 UTC, Santiagoebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/Api/Customers.php
> +            if($this->optInStatusForStore) {
Add a blank space after **if** and before **(** for better readability

2019-06-14 19:41 UTC, Santiagoebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
> +     * @return false|Mage_Core_Model_Abstract
Change return type to Mage_Newsletter_Model_Subscriber

2019-06-14 19:44 UTC, Santiagoebizmarts commented on app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
> +        $helper = $this->getMailChimpHelper();
Is it necessary to do this or is it already done in the createBatchJson function?

2019-06-17 13:23 UTC, centerax requested changes
Please add a meaningful name to the PR.

2019-06-19 14:42 UTC, SantiParagarino approved these changes

2019-06-25 19:38 UTC, SantiParagarino approved these changes

2019-06-26 14:17 UTC, centerax approved these changes

2019-06-26 14:51 UTC, merged